server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://ocalhost:8761/eureka
spring:
  application:
    name: EUREKA-SERVER
